# Generated by Django 2.0.7 on 2018-08-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioupload', '0002_filemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileNameModel',
        ),
    ]
